---
- hosts: localhost
  user: vagrant
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - cocooma.homebrew
    - cocooma.dotfiles

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/preferences.yml
    - include: tasks/gem_packages.yml
    - include: tasks/pip_packages.yml
    - include: tasks/macports_packages.yml
    - include: tasks/zsh_setup.yml
    - include: tasks/iterm2_bg_hostname_setup.yml

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    - name: Run .osx dotfiles.
      shell: ~/.osx --no-restart
      changed_when: false
