---
# Custom Terminal theme.
# - name: Get current Terminal profile.
#   shell: defaults read com.apple.terminal 'Default Window Settings'
#   register: terminal_theme
#   changed_when: false
#
# - name: Ensure custom Terminal profile is added.
#   shell: open files/terminal/JJG-Term.terminal
#   changed_when: false
#   when: "'JJG-Term' not in terminal_theme.stdout"
#
# # TODO: This doesn't work in Yosemite. Consider a different solution?
# - name: Ensure custom Terminal profile is set as default.
#   shell: "{{ item }}"
#   with_items:
#     - defaults write com.apple.terminal 'Default Window Settings' -string JJG-Term
#     - defaults write com.apple.terminal 'Startup Window Settings' -string JJG-Term
#   changed_when: false
#   when: "'JJG-Term' not in terminal_theme.stdout"

# Sudoers configuration (enables more convenient Vagrant usage).
- name: Copy sudoers configuration into place.
  copy:
    src: files/etc/sudoers
    dest: /etc/sudoers
    mode: 0440
    validate: 'visudo -cf %s'
  sudo: yes
  when: configure_sudoers

# Setup touch_id pam monudle and config
- name: Copy sudo pam lib for touch_id
  copy:
    src: files/usr/local/lib/pam
    dest: /usr/local/lib
    directory_mode: yes
    mode: 0444
    owner: "root"
    group: "wheel"
  sudo: yes
  when: configure_sudoers

- name: Copy sudo config for touch_id
  copy:
    src: files/etc/pam.d/sudo
    dest: /etc/pam.d/sudo
    mode: 0444
    owner: "root"
    group: "wheel"
  sudo: yes
  when: configure_sudoers

# Sudoers configuration (enables more convenient Vagrant usage).
- name: Export Path
  copy:
    src: files/etc/bashrc
    dest: /etc/bashrc
    mode: 0444
  sudo: yes
